
[modules]

	[modules.everpotion]
		crafting = true

	[modules.fruittrees]
		cherry = true
		hybridization = true

[client]
	#Show item tags and nbt in advanced tooltips
	debugTooltip = true
	#Max line width shown in description of tooltips
	#Range: > 50
	tooltipWrapWidth = 500
	#Show customized tooltips from any item. Mainly for pack devs
	globalTooltip = true
	#Allowed values: vanilla, kiwi
	debugTooltipNBTFormatter = "vanilla"
	contributorEffect = ""

