#Range: 0 ~ 15
cactusGrowAge = 5
nerfSeaPickle = true
noAIEntities = ["snow_golem"]
peacefulNetherStar = true
blockResistance = ["mekanismgenerators:reactor_glass=2000", "mekanismgenerators:fusion_reactor_frame=2000", "brown_concrete=10", "blue_concrete=7"]
itemContainer = []

