[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.1
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
    [[effects.attributes]]
        name = "minecraft:generic.knockback_resistance"
        operation = "add"
        amount = 0.1
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.2
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
    [[effects.attributes]]
        name = "minecraft:generic.knockback_resistance"
        operation = "add"
        amount = 0.1
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.3
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 4.0
    [[effects.attributes]]
        name = "minecraft:generic.movement_speed"
        operation = "multiply_base"
        amount = 0.1
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.4
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
	[[effects.attributes]]
        name = "minecraft:generic.attack_damage"
        operation = "add"
        amount = 1.0
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.5
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
    [[effects.attributes]]
        name = "minecraft:generic.attack_speed"
        operation = "multiply_total"
        amount = 0.1
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.6
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
	[[effects.attributes]]
        name = "minecraft:generic.attack_damage"
        operation = "add"
        amount = 1.0
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.7
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 4.0
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "all"
        above = 0.8
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.movement_speed"
        operation = "multiply_base"
        amount = 0.15
    [[effects.status_effects]]
        name = "minecraft:hunger"
        power = 2
    [[effects.conditions]]
        groups = ["sugars"]
        match = "all"
        above = 0.8
        below = 1.0

[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.movement_speed"
        operation = "multiply_base"
        amount = 0.1
    [[effects.conditions]]
        groups = ["sugars"]
        match = "all"
        above = 0.4
        below = 1.0