
[general]
	#The blocks whose hardness should be modified. This needs to be the registry name of the block followed by an @ followed by the new hardness, so for example: 'minecraft:stone@5'
	tweak_hardness = [ 'stone@2.5', 'iron_ore@10', 'gold_ore@10', 'coal_ore@10', 'redstone_ore@10', 'diamond_ore@15', 'lapis_ore@10', 'nether_quartz_ore@10', 'emerald_ore@15', 'obsidian@100' ]
	#The blocks whose mining level should be modified. This needs to be the registry name of the block followed by an @ followed by the tool class ('pickaxe', 'axe' or 'shovel') followed by an @ followed by the harvest level (0 = wood, 1 = stone, 2 = iron, 3 = diamond, custom levels work), so for example: 'minecraft:stone@pickaxe@2'
	tweak_mining_level = [ 'diamond_ore@pickaxe@3' ]
